data:
  batch_size: 20
  validation_multiplier: 0.3
  num_workers: 4
  path: "./data/"
model:
  baseline: efficientnet_v2_m
  weights: IMAGENET1K_V1
  device: cuda
  learning_rate: 0.001
  num_epochs: 30
  step_size: 10
