data:
  batch_size: 20
  validation_multiplier: 0.3
  num_workers: 4
  path: "./data/"
model:
  baseline: resnet152
  weights: DEFAULT
  device: cuda
  learning_rate: 0.00001
  num_epochs: 20
  step_size: 10
